### ISSUE TITLE
train_aug.txt

### ISSUE THREAD

**Issue by AmingWu** [cvlab-yonsei/JoEm#1]
Dear Authors,

When I run your code, there is an error:

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/PASCALVOC/VOCdevkit/VOC2012/ImageSets/Segmentation/train_aug.txt'

Could you tell me how to get train_aug.txt?

**Comment by dh-baek** [comment]
You can download the file from the link below.

https://github.com/cvlab-yonsei/JoEm/releases/download/v1.0/train_aug.txt
