### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by zaiquanyang** [cvlab-yonsei/JoEm#4]
After introducing the SBD (Semantic Boundary Dataset), what kind of split (train_split and test_split include how many images ) is adopted by this paper?

**Comment by dh-baek** [comment]
As mentioned in our paper, we utilized a total of 10,582 training samples for PASCAL VOC by introducing the SBD. The file names can be obtained from the '[training_aug.txt](https://github.com/cvlab-yonsei/JoEm/releases/download/v1.0/train_aug.txt)' file. For validation, we employed the original 1,449 validation samples.
