### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Yi-Qi638** [cvlab-yonsei/JoEm#5]
Thank you for your work～

self._cat_dir = self._base_dir / ("%d_labels.pth" % (self.n_categories)) 

Could  you tell me how to generate the "59_labels.pth" file of the context dataset?

**Comment by dh-baek** [comment]
This is the link to get the file.
https://github.com/cvlab-yonsei/JoEm/releases/download/v1.0/59_labels.pth
